filein "Dolphin/Core/Object Arts/Dolphin/Base/Object.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Magnitude.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/ArithmeticValue.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Number.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Integer.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/SmallInteger.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Collection.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/SequenceableCollection.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/ArrayedCollection.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Array.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/String.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Boolean.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Association.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Exception.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Error.cls".
filein "Dolphin/Core/Object Arts/Dolphin/Base/Notification.cls".
filein "dolphin-core/stubs/sunit-stubs.st".
filein "Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestFailure.cls".
filein "Dolphin/Core/Contributions/Camp Smalltalk/SUnit/ResumableTestFailure.cls".
filein "Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestSkip.cls".
filein "Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestCaseResult.cls".
filein "Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestResult.cls".
filein "Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestCase.cls".
quit
