filein /mnt/c/programming/ZigSmalltalk/Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestFailure.cls
filein /mnt/c/programming/ZigSmalltalk/Dolphin/Core/Contributions/Camp Smalltalk/SUnit/ResumableTestFailure.cls
filein /mnt/c/programming/ZigSmalltalk/Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestSkip.cls
filein /mnt/c/programming/ZigSmalltalk/Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestCaseResult.cls
filein /mnt/c/programming/ZigSmalltalk/Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestResult.cls
filein /mnt/c/programming/ZigSmalltalk/Dolphin/Core/Contributions/Camp Smalltalk/SUnit/TestCase.cls

TestCase new assert: false.
